### ISSUE TITLE
KeyError: 'target'

### ISSUE THREAD

**Issue by CuypersBart** [HelmholtzAI-Consultants-Munich/fg-clustering#13]
Hi, when running:
"fgc = FgClustering(model=model, data=df, target_column='target')"
I get the key error below. 

Do you know what could be going wrong? I tried renaming the 'y-label' column 'target', but this did not help. 

> `KeyError                                  Traceback (most recent call last)
> Input In [884], in <cell line: 9>()
>       7 # initialize and run fgclustering object
>       8 fgc = FgClustering(model=model, data=df2, target_column='target')
> ----> 9 fgc.run(max_iter_clustering = 20)
> 
> File ~/miniconda3/lib/python3.9/site-packages/fgclustering/forest_guided_clustering.py:94, in FgClustering.run(self, number_of_clusters, max_K, bootstraps_JI, max_iter_clustering, discart_value_JI)
>      91     print(f"Use {self.k} as number of cluster")
>      93 self.cluster_labels = KMedoids(n_clusters=self.k, random_state=self.random_state).fit(self.distance_matrix).labels_
> ---> 94 self._X_ranked, self.p_value_of_features = stats.calculate_global_feature_importance(self.X, self.y, self.cluster_labels)
> 
> File ~/miniconda3/lib/python3.9/site-packages/fgclustering/statistics.py:188, in calculate_global_feature_importance(X, y, cluster_labels)
>     185         p_value_of_features[feature] = anova_p_value
>     187 X_ranked = _rank_features(X, y, p_value_of_features)
> --> 188 X_ranked = _sort_clusters_by_target(X_ranked)
>     189 X_ranked.sort_values(by=['cluster','target'], axis=0, inplace=True)
>     191 return X_ranked, p_value_of_features
> 
> File ~/miniconda3/lib/python3.9/site-packages/fgclustering/statistics.py:143, in _sort_clusters_by_target(X_ranked)
>     135 def _sort_clusters_by_target(X_ranked):
>     136     '''Sort clusters by mean target values in clusters. 
>     137 
>     138     :param X_ranked: Filtered and ranked feature matrix.
>    (...)
>     141     :rtype: pandas.DataFrame
>     142     '''
> --> 143     means = X_ranked.groupby(['cluster']).mean().sort_values(by='target',ascending=True)
>     144     means['target'] = range(means.shape[0])
>     145     mapping = dict(means['target'])
> 
> File ~/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py:311, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
>     305 if len(args) > num_allow_args:
>     306     warnings.warn(
>     307         msg.format(arguments=arguments),
>     308         FutureWarning,
>     309         stacklevel=stacklevel,
>     310     )
> --> 311 return func(*args, **kwargs)
> 
> File ~/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py:6313, in DataFrame.sort_values(self, by, axis, ascending, inplace, kind, na_position, ignore_index, key)
>    6309 elif len(by):
>    6310     # len(by) == 1
>    6312     by = by[0]
> -> 6313     k = self._get_label_or_level_values(by, axis=axis)
>    6315     # need to rewrap column in Series to apply key function
>    6316     if key is not None:
>    6317         # error: Incompatible types in assignment (expression has type
>    6318         # "Series", variable has type "ndarray")
> 
> File ~/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py:1840, in NDFrame._get_label_or_level_values(self, key, axis)
>    1838     values = self.axes[axis].get_level_values(key)._values
>    1839 else:
> -> 1840     raise KeyError(key)
>    1842 # Check for duplicates
>    1843 if values.ndim > 1:
> 
> KeyError: 'target'`

![image](https://user-images.githubusercontent.com/9530810/195150861-08b44ef4-20f3-4c0e-ab94-60d70aeb4216.png)

**Comment by hpelin** [comment]
@CuypersBart Thanks for your feedback. We are aware of the issue and will fix it with the next release. In the meantime, you could encode your target column, e.g. with LabelEncoder.

**Comment by lisa-sousa** [comment]
Dear @CuypersBart we just released a new package version where this issue is fixed! You can now use categorical target values as input.
